apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudbeaver.fullname" . }}
  labels:
    app: {{ include "cloudbeaver.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloudbeaver.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cloudbeaver.name" . }}
    spec:
      containers:
        - name: cloudbeaver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8978
          env:
            - name: CB_SERVER_PORT
              value: "8978"
