apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudbeaver.fullname" . }}
spec:
  selector:
    app: {{ include "cloudbeaver.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8978
  type: {{ .Values.service.type }}
