apiVersion: apps/v1
kind: Deployment
metadata:
  name: wren-ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wren-ai-service
  template:
    metadata:
      labels:
        app: wren-ai-service
    spec:
      containers:
        - name: wren-ai-service
          image: ghcr.io/canner/wren-ai-service:{{ .Values.env.WREN_AI_SERVICE_VERSION }}
          ports:
            - containerPort: {{ .Values.env.WREN_AI_SERVICE_PORT }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: CONFIG_PATH
              value: /app/data/config.yaml
          envFrom:
            - configMapRef:
                name: wrenai-env
          volumeMounts:
            - name: config
              mountPath: /app/data/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: wrenai-config
