apiVersion: v1
kind: Service
metadata:
  name: wren-ai-service
spec:
  selector:
    app: wren-ai-service
  ports:
    - port: {{ .Values.env.WREN_AI_SERVICE_PORT }}
      targetPort: {{ .Values.env.WREN_AI_SERVICE_PORT }}
  type: ClusterIP
