apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: {{ .Values.namespace }}
  labels:
    app: pgadmin

data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL",
          "Group": "Servers",
          "Host": "postgres",
          "Port": 5432,
          "MaintenanceDB": "{{ .Values.postgres.database }}",
          "Username": "{{ .Values.postgres.username }}",
          "TunnelPort": "22",
          "KerberosAuthentication": false,
          "ConnectionParameters": {
            "sslmode": "prefer",
            "passfile": "/pgadmin4/pgpass"
          }
        }
      }
    }
