apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: {{ .Values.pgadmin.service.port }}
      targetPort: 80
