apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mysql-phpmyadmin-wrenai.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mysql-phpmyadmin-wrenai.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.create }}
automountServiceAccountToken: true
{{- end }}
