postgres:
  image: postgres:15
  username: admin
  password: adminpass
  database: mydatabase
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: nvmetwo

pgadmin:
  image: dpage/pgadmin4
  email: admin@admin.com
  password: adminpass
  db_password: adminpass
  service:
    type: ClusterIP
    port: 80

namespace: postgres-pgadmin
